### ISSUE TITLE
params.key approach not working anymore till paging-version 3.0.0alpha013

### ISSUE THREAD

**Issue by Berki2021** [alexmamo/FirestorePagination#1]
Hello,

I appreciate your repository very much, thanks for the work. The only problem I now have is, that this approach is not working anymore as we have to implement `getRefreshKey(state: PagingState<QuerySnapshot, Product>): QuerySnapshot?` in the pagingSource. Do you have an Idea how to do so?

**Comment by AlexMamo** [comment]
Hi, Berki2021. Because we aren't using Room for this example, instead we are using Firestore, there is no need to do something special. We just need to override the new method and return null. See below in the docs:
https://developer.android.com/topic/libraries/architecture/paging/v3-network-db#kotlin
Just updated the repo ;)

**Comment by Berki2021** [comment]
Thank you very much
